### ISSUE TITLE
Can you add a Releases?

### ISSUE THREAD

**Issue by daannorris** [ststeiger/sql_profiler#2]
It would be great if i dont have to compile by myself.

**Comment by ststeiger** [comment]
Compiling from source is no tragedy ;)
Besides, on the [release page](https://github.com/ststeiger/sql_profiler/releases) you can download [sql_profiler.zip](https://github.com/ststeiger/sql_profiler/releases/download/1.0/sql_profiler.zip), which if I remember right contains executables for the following platforms: 
 - Windows-x86
 - Windows-amd64
 - Linux-amd64
 - Linux-arm32
 - Mac OSX-amd64 (>= Sierra - 10.12+)


Not the very latest release, that one contained a styling bug (just the text color of some keywords, not a crash), but otherwise fine.

**Comment by daannorris** [comment]
Im sorry, i didnt see the release page, thank you
